export * from './about/About';
export * from './events/Events';
export * from './events/EventsDetail/EventsDetail';
export * from './home/Home';
export * from './profile/Profile';
export * from './validate-user/ValidateUser';
export * from './confirm-account/Confirm';
export * from './createEvent/CreateEvent'
export * from './events/Events';
export * from './forgot-password/ForgotPassword';
export * from './forgot-password/SendRecoveryEmail';
